use crate::service::AuthError;

async fn validate_credentials() 